import { getValidToken } from './auth'

const BASE = 'https://api.spotify.com/v1'

async function apiFetch(path, options = {}) {
  const token = await getValidToken()
  if (!token) throw new Error('Not authenticated')

  // Only set Content-Type for POST/PUT requests — GET requests break with it
  const headers = { Authorization: `Bearer ${token}` }
  if (options.body) headers['Content-Type'] = 'application/json'

  const res = await fetch(`${BASE}${path}`, {
    ...options,
    headers: { ...headers, ...(options.headers || {}) },
  })

  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err?.error?.message || `API error ${res.status}`)
  }
  return res.json()
}

export const MAX_POPULARITY = 50

const SEARCH_SEEDS = [
  { q: 'tag:hipster', label: 'hipster' },
  { q: 'genre:ambient', label: 'ambient' },
  { q: 'genre:folk', label: 'folk' },
  { q: 'genre:jazz', label: 'jazz' },
  { q: 'genre:classical', label: 'classical' },
  { q: 'genre:blues', label: 'blues' },
  { q: 'genre:indie', label: 'indie' },
  { q: 'genre:soul', label: 'soul' },
  { q: 'tag:hipster year:2000-2010', label: '00s hipster' },
  { q: 'tag:hipster year:1990-2000', label: '90s hipster' },
  { q: 'tag:hipster year:1980-1990', label: '80s hipster' },
  { q: 'tag:hipster year:2010-2020', label: '10s hipster' },
]

async function fetchTracks(query, maxPop = MAX_POPULARITY, count = 15) {
  const offset = Math.floor(Math.random() * 700)
  const params = new URLSearchParams({ q: query, type: 'track', limit: 50, offset })
  const data = await apiFetch(`/search?${params}`)
  const items = data.tracks?.items || []

  return items
    .filter(t => {
      if (!t || !t.id) return false
      const pop = t.popularity
      // null/undefined = unscored = ultra-obscure, always include
      return pop === null || pop === undefined || pop <= maxPop
    })
    .sort((a, b) => (a.popularity ?? 0) - (b.popularity ?? 0))
    .slice(0, count)
    .map(normalizeTrack)
}

export async function fetchDiscoveryFeed(maxPop = MAX_POPULARITY) {
  const seeds = shuffleArray(SEARCH_SEEDS).slice(0, 6)
  const results = await Promise.allSettled(seeds.map(s => fetchTracks(s.q, maxPop, 12)))
  const tracks = results.filter(r => r.status === 'fulfilled').flatMap(r => r.value)
  const seen = new Set()
  return tracks.filter(t => { if (seen.has(t.id)) return false; seen.add(t.id); return true })
}

export async function fetchLowPopularityTracks(query, maxPop = MAX_POPULARITY, count = 15) {
  return fetchTracks(query, maxPop, count)
}

export async function searchLowPopularityTracks(query, maxPop = MAX_POPULARITY) {
  const [direct, hipster] = await Promise.allSettled([
    fetchTracks(query, maxPop, 25),
    fetchTracks(`tag:hipster ${query}`, maxPop, 15),
  ])
  const combined = [
    ...(direct.status === 'fulfilled' ? direct.value : []),
    ...(hipster.status === 'fulfilled' ? hipster.value : []),
  ]
  const seen = new Set()
  return combined.filter(t => { if (seen.has(t.id)) return false; seen.add(t.id); return true }).slice(0, 40)
}

export async function getCurrentUser() { return apiFetch('/me') }

export async function createPlaylist(userId, tracks) {
  const playlist = await apiFetch(`/users/${userId}/playlists`, {
    method: 'POST',
    body: JSON.stringify({
      name: '🟢 Potsify — Undiscovered Tracks',
      description: 'The forgotten side of Spotify. Generated by Potsify.',
      public: true,
    }),
  })
  const uris = tracks.map(t => `spotify:track:${t.id}`)
  for (let i = 0; i < uris.length; i += 100) {
    await apiFetch(`/playlists/${playlist.id}/tracks`, {
      method: 'POST',
      body: JSON.stringify({ uris: uris.slice(i, i + 100) }),
    })
  }
  return playlist
}

function normalizeTrack(t) {
  return {
    id: t.id,
    name: t.name,
    artists: t.artists.map(a => a.name),
    album: t.album.name,
    albumArt: t.album.images?.[1]?.url || t.album.images?.[0]?.url || null,
    popularity: t.popularity ?? 0,
    previewUrl: t.preview_url,
    spotifyUrl: t.external_urls?.spotify,
    uri: t.uri,
    durationMs: t.duration_ms,
  }
}

function shuffleArray(arr) {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

export { SEARCH_SEEDS }
