import { getValidToken } from './auth'

const BASE = 'https://api.spotify.com/v1'

async function apiFetch(path, options = {}) {
  const token = await getValidToken()
  if (!token) throw new Error('Not authenticated')
  const res = await fetch(`${BASE}${path}`, {
    ...options,
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...(options.headers || {}) },
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err?.error?.message || `API error ${res.status}`)
  }
  return res.json()
}

export const MAX_POPULARITY = 50

// tag:hipster is Spotify's built-in low-popularity filter — returns hundreds of obscure tracks
// Combine with different search seeds for variety
const SEARCH_SEEDS = [
  'tag:hipster',
  'tag:hipster year:2000-2010',
  'tag:hipster year:1990-2000',
  'tag:hipster year:2010-2020',
  'tag:hipster year:1980-1990',
  'tag:hipster year:1970-1980',
  'tag:hipster year:2020-2024',
  'tag:hipster year:1960-1970',
]

export async function fetchLowPopularityTracks(query, maxPop = MAX_POPULARITY, count = 15) {
  const offset = Math.floor(Math.random() * 800)
  const params = new URLSearchParams({ q: query, type: 'track', limit: 50, offset })
  const data = await apiFetch(`/search?${params}`)
  const tracks = data.tracks?.items || []

  return tracks
    .filter((t) => {
      if (!t) return false
      // null popularity = ultra-obscure, treat as 0 — always include
      const pop = t.popularity ?? 0
      return pop <= maxPop
    })
    .sort((a, b) => (a.popularity ?? 0) - (b.popularity ?? 0))
    .slice(0, count)
    .map(normalizeTrack)
}

export async function fetchDiscoveryFeed(maxPop = MAX_POPULARITY, perQuery = 10) {
  const seeds = shuffleArray(SEARCH_SEEDS).slice(0, 6)
  const results = await Promise.allSettled(seeds.map((q) => fetchLowPopularityTracks(q, maxPop, perQuery)))
  const tracks = results.filter((r) => r.status === 'fulfilled').flatMap((r) => r.value)
  const seen = new Set()
  return tracks.filter((t) => { if (seen.has(t.id)) return false; seen.add(t.id); return true })
}

export async function searchLowPopularityTracks(query, maxPop = MAX_POPULARITY) {
  const params = new URLSearchParams({ q: query, type: 'track', limit: 50 })
  const data = await apiFetch(`/search?${params}`)
  const tracks = data.tracks?.items || []
  return tracks
    .filter((t) => t && (t.popularity ?? 0) <= maxPop)
    .sort((a, b) => (a.popularity ?? 0) - (b.popularity ?? 0))
    .slice(0, 40)
    .map(normalizeTrack)
}

export async function getCurrentUser() { return apiFetch('/me') }

export async function createPlaylist(userId, tracks) {
  const playlist = await apiFetch(`/users/${userId}/playlists`, {
    method: 'POST',
    body: JSON.stringify({ name: '🟢 Potsify — Undiscovered Tracks', description: 'The forgotten side of Spotify. Generated by Potsify.', public: true }),
  })
  const uris = tracks.map((t) => `spotify:track:${t.id}`)
  for (let i = 0; i < uris.length; i += 100) {
    await apiFetch(`/playlists/${playlist.id}/tracks`, { method: 'POST', body: JSON.stringify({ uris: uris.slice(i, i + 100) }) })
  }
  return playlist
}

function normalizeTrack(t) {
  return {
    id: t.id, name: t.name, artists: t.artists.map((a) => a.name),
    album: t.album.name, albumArt: t.album.images?.[1]?.url || t.album.images?.[0]?.url || null,
    popularity: t.popularity ?? 0, previewUrl: t.preview_url,
    spotifyUrl: t.external_urls?.spotify, uri: t.uri, durationMs: t.duration_ms,
  }
}

function shuffleArray(arr) {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]] }
  return a
}

export { SEARCH_SEEDS }
