import { getValidToken } from './auth'

const BASE = 'https://api.spotify.com/v1'

async function apiFetch(path, options = {}) {
  const token = await getValidToken()
  if (!token) throw new Error('Not authenticated')

  const res = await fetch(`${BASE}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      ...(options.headers || {}),
    },
  })

  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err?.error?.message || `API error ${res.status}`)
  }

  return res.json()
}

export const MAX_POPULARITY = 50

// Year-range queries — much more reliable than genre: filters
const SEARCH_QUERIES = [
  'year:2000-2005',
  'year:1995-2000',
  'year:2005-2010',
  'year:1990-1995',
  'year:2010-2015',
  'year:1985-1990',
  'year:2015-2018',
  'year:1980-1985',
  'year:2018-2021',
  'year:1975-1980',
  'year:1970-1975',
  'year:2021-2023',
]

export async function fetchLowPopularityTracks(query, maxPop = MAX_POPULARITY, count = 20) {
  const offset = Math.floor(Math.random() * 500)

  const params = new URLSearchParams({
    q: query,
    type: 'track',
    limit: 50,
    offset,
    market: 'US',
  })

  const data = await apiFetch(`/search?${params}`)
  const tracks = data.tracks?.items || []

  return tracks
    .filter((t) => t && typeof t.popularity === 'number' && t.popularity <= maxPop)
    .sort((a, b) => a.popularity - b.popularity)
    .slice(0, count)
    .map(normalizeTrack)
}

export async function fetchDiscoveryFeed(maxPop = MAX_POPULARITY, perQuery = 8) {
  const queries = shuffleArray(SEARCH_QUERIES).slice(0, 6)

  const results = await Promise.allSettled(
    queries.map((q) => fetchLowPopularityTracks(q, maxPop, perQuery))
  )

  const tracks = results
    .filter((r) => r.status === 'fulfilled')
    .flatMap((r) => r.value)

  const seen = new Set()
  return tracks.filter((t) => {
    if (seen.has(t.id)) return false
    seen.add(t.id)
    return true
  })
}

export async function searchLowPopularityTracks(query, maxPop = MAX_POPULARITY) {
  const params = new URLSearchParams({
    q: query,
    type: 'track',
    limit: 50,
    market: 'US',
  })

  const data = await apiFetch(`/search?${params}`)
  const tracks = data.tracks?.items || []

  return tracks
    .filter((t) => t && typeof t.popularity === 'number' && t.popularity <= maxPop)
    .sort((a, b) => a.popularity - b.popularity)
    .slice(0, 40)
    .map(normalizeTrack)
}

export async function getCurrentUser() {
  return apiFetch('/me')
}

export async function createPlaylist(userId, tracks) {
  const playlist = await apiFetch(`/users/${userId}/playlists`, {
    method: 'POST',
    body: JSON.stringify({
      name: '🟢 Potsify — Undiscovered Tracks',
      description: 'Songs with low popularity score — the forgotten side of Spotify. Generated by Potsify.',
      public: true,
    }),
  })

  const uris = tracks.map((t) => `spotify:track:${t.id}`)
  for (let i = 0; i < uris.length; i += 100) {
    await apiFetch(`/playlists/${playlist.id}/tracks`, {
      method: 'POST',
      body: JSON.stringify({ uris: uris.slice(i, i + 100) }),
    })
  }

  return playlist
}

function normalizeTrack(t) {
  return {
    id: t.id,
    name: t.name,
    artists: t.artists.map((a) => a.name),
    album: t.album.name,
    albumArt: t.album.images?.[1]?.url || t.album.images?.[0]?.url || null,
    popularity: t.popularity,
    previewUrl: t.preview_url,
    spotifyUrl: t.external_urls?.spotify,
    uri: t.uri,
    durationMs: t.duration_ms,
  }
}

function shuffleArray(arr) {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

export { SEARCH_QUERIES }
